### PR TITLE
Add unit test for goutil package

### PR DESCRIPTION
**Pull request by KEINOS**
This PR will cover the `gup/internal/goutil`.

- [x] Add initial test to draft a PR
- [x] Add examples for public functions in `goutil` package to cover the basics
- [x] Add examples for public methods
- [x] Add tests for failed/error cases
- [x] Apply dependency injection to enable mock/monkey-patch
- [x] cover `gouil` up to 100%

### CODE REVIEW

**Comment by nao1215** [comment]
@KEINOS 
Your way of making unit tests is more careful than mine. Perhaps I will be satisfied enough with the tests you write in the future.

>cover gouil up to 100%

You don't have to force yourself to aim for 100% coverage.
Coverage of 80% or more is sufficient.

**Comment by KEINOS** [comment]
@nao1215 

I think it's ready! 👍 Please review it when you got time 🤞

**Comment by nao1215** [comment]
@KEINOS 
LGTM.
However, I do not know if the test will work on Windows.
Please merge the code from the main branch when you have time :pray: 

Currently, the test passes on Linux, Mac, and Windows.
However, Mac and Windows may fail the test in rare cases due to an exceedance of the Race condition.

**Comment by KEINOS** [comment]
Windows...

**Comment by nao1215** [comment]
Windows...

**Comment by KEINOS** [comment]
@nao1215 

**Sorry, I was wrong** about the above comment. **It IS my bad**.

https://github.com/nao1215/gup/actions/runs/3079250233/jobs/4975350665#step:4:253

**Comment by nao1215** [comment]
@KEINOS 
You need to fix "--- FAIL" ar "Run unit test" result.
Windows has a different separator for file paths, so the hard-coded paths must be replaced with filepath.Join().

**Comment by KEINOS** [comment]
> Windows has a different separator for file paths

Linux「Windows...」
macOS「Windows...」
UNIX「Indeed」

**Comment by KEINOS** [comment]
[MEMO]: Differences of module paths between platforms

## macOS

```shellsession
$ go version -m "$(which gup)"
/Users/admin/go/bin/gup: go1.19.1
        path    github.com/nao1215/gup
        mod     github.com/nao1215/gup  v0.10.5 h1:kQKlfrQyNIBq4DlOKB26oLOFHStszgxSnTKyOtdMJbM=
        dep     github.com/fatih/color  v1.13.0 h1:8LOYc1KYPPmyKMuN8QV2DNRWNbLo6LZ0iLs8+mlH53w=
        dep     github.com/gen2brain/beeep      v0.0.0-20210529141713-5586760f0cc1      h1:Xh9mvwEmhbdXlRSsgn+N0zj/NqnKvpeqL08oKDHln2s=
        dep     github.com/mattn/go-colorable   v0.1.12 h1:jF+Du6AlPIjs2BiUiQlKOX0rt3SujHxPnksPKZbaA40=
        dep     github.com/mattn/go-isatty      v0.0.14 h1:yVuAays6BHfxijgZPzw+3Zlu5yQgKGP2/hcQbHb7S9Y=
        dep     github.com/spf13/cobra  v1.5.0  h1:X+jTBEBqF0bHN+9cSMgmfuvv2VHJ9ezmFNf9Y/XstYU=
        dep     github.com/spf13/pflag  v1.0.5  h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
        dep     golang.org/x/sys        v0.0.0-20220412211240-33da011f77ad      h1:ntjMns5wyP/fN65tdBD4g8J5w8n015+iIIs9rtjXkY0=
        build   -compiler=gc
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=amd64
        build   GOOS=darwin
        build   GOAMD64=v1
```

## Linux (Debian, Docker+`golang:latest`)

```shellsession
# go version -m "$(which gup)"
/go/bin/gup: go1.19.1
        path    github.com/nao1215/gup
        mod     github.com/nao1215/gup  v0.10.5 h1:kQKlfrQyNIBq4DlOKB26oLOFHStszgxSnTKyOtdMJbM=
        dep     github.com/fatih/color  v1.13.0 h1:8LOYc1KYPPmyKMuN8QV2DNRWNbLo6LZ0iLs8+mlH53w=
        dep     github.com/gen2brain/beeep      v0.0.0-20210529141713-5586760f0cc1      h1:Xh9mvwEmhbdXlRSsgn+N0zj/NqnKvpeqL08oKDHln2s=
        dep     github.com/godbus/dbus/v5       v5.0.3  h1:ZqHaoEF7TBzh4jzPmqVhE/5A1z9of6orkAe5uHoAeME=
        dep     github.com/mattn/go-colorable   v0.1.12 h1:jF+Du6AlPIjs2BiUiQlKOX0rt3SujHxPnksPKZbaA40=
        dep     github.com/mattn/go-isatty      v0.0.14 h1:yVuAays6BHfxijgZPzw+3Zlu5yQgKGP2/hcQbHb7S9Y=
        dep     github.com/spf13/cobra  v1.5.0  h1:X+jTBEBqF0bHN+9cSMgmfuvv2VHJ9ezmFNf9Y/XstYU=
        dep     github.com/spf13/pflag  v1.0.5  h1:iy+VFUOCP1a+8yFto/drg2CJ5u0yRoB7fZw3DKv/JXA=
        dep     golang.org/x/sys        v0.0.0-20220412211240-33da011f77ad      h1:ntjMns5wyP/fN65tdBD4g8J5w8n015+iIIs9rtjXkY0=
        build   -compiler=gc
        build   CGO_ENABLED=1
        build   CGO_CFLAGS=
        build   CGO_CPPFLAGS=
        build   CGO_CXXFLAGS=
        build   CGO_LDFLAGS=
        build   GOARCH=amd64
        build   GOOS=linux
        build   GOAMD64=v1
```

**Comment by nao1215** [comment]
@KEINOS 
Excellent, the test passed!! You are now friends with Windows.
The test I made seems to fail frequently. I will fix it next time.

**Pull request merged**
