### PR TITLE
Add platform test workflow

### PR DESCRIPTION
**Pull request by nao1215**
gup command may check standard output and standard errors in unit tests.
We know that error messages vary from platform to platform and that tests fail in some environments.

gup command returns an error message that is a concatenation of the "message executed for the gup command" and the "message returned by the golang standard package". Error messages returned by Golang's standard packages are platform-dependent.

To solve this problem I will add the github actions workflow(#44) to test on windows, mac and linux.

### CODE REVIEW

**Comment by nao1215** [comment]
Windows...

**Comment by KEINOS** [comment]
Windows...

**Comment by nao1215** [comment]
Windows, I haven't seen your face for ten years and I almost forgot about you. 
However, I will remember you for the next ten years as well. I can't believe you failed so many unit tests.

**Comment by nao1215** [comment]
＼( 'ω')／ウオオオオオアアアーーーッ！

**Pull request merged**
