### PR TITLE
Use buildinfo

### PR DESCRIPTION
**Pull request by mattn**
Use debug/buildinfo to avoid to spawn "go version -m" for each binary files.

### CODE REVIEW

**Comment by nao1215** [comment]
@mattn 
Thank you for PR! The build is broken, but it will be merged.

This is the second time you have commented.
At first, I didn't know you were famous. Now, I know it.

**Comment by mattn** [comment]
Ooops. Sorry. debug/buildinfo is not released 🙇

**Comment by mattn** [comment]
Feel free to revert this.

**Comment by nao1215** [comment]
Merge after go 1.18 is released.
I will revert once.

**Pull request merged**
